name: AkarinVS_builds

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      shell: cmd
      run: |
        .\lsw-build-AkarinVS.bat
        
    - uses: actions/upload-artifact@v2
      with:
        name: AkarinVS_builds
        path: L-SMASH-Works-AkarinVS*.zip
